;Autor:Calle Condori Rorigo
;USO DE LA INSTRUCCIÓN SUBWF
;RESTAR  16-3

DATO1     EQU    0X20    ;AQUI SE GUARDA LOS DATOS
DATO2     EQU    0X21
RESULTADO EQU    0X22
PROGRAMA:
          MOVLW  D'16'   ;MOVER EL 16 AL REGISTRO DE TRABAJO
          MOVWF  DATO1   ;MOVER EL VALOR DEL REGISTRO DE TRABAJO AL REGISTRO DATO1
          MOVLW  D'3'    ;MOVER EL 3 AL REGISTRO DE TRABAJO
          MOVWF  DATO2   ;MOVER EL REGISTRO DE TRABAJO AL REGISTRO DATO2

RESTA:
          MOVF  DATO2,W  ;MOVER EL VALOR DEL REGISTRO DATO2 AL REGISTRO DE TRABAJO
          SUBWF DATO1,W  ;REALIZA LA RESTA W=DATO1-W
          MOVWF RESULTADO;GUARDA EL VALOR DEL REGISTRO DE TRABAJO AL REGISTRO RESULTADO
INFINITO:
          GOTO  INFINITO ;BUCLE INFINITO
          END