;LO QUE HACE EL RRF ES RECORRER HACIA EL LADO DERECHO UN BIT A NIVEL BIT
;SI 20 = 0001 0100 APLICANDO RRF 10 = 0000 1010
;EN FORMA DECIMAL EL RESULTADO ES COMO SI FUERA CUALCQUIER NUMERO 
;ESTUBIERA SIENDO DIVIDIDO POR 2
          ORG    0X00
          GOTO   INICIO
          ORG    0X05
INICIO:
          MOVLW  D'20'
          MOVWF  0X0C
          RRF    0X0C,W
          MOVWF  0X0D
          END