;Autor: Calle Condori Rodrigo
;INCREMENTO DE 0 AL 5 DE UNO EN UNO
	LIST P=16F877A
	INCLUDE <P16F877A.INC>
    DATO_1    EQU  0X20            ;DIRECCION DE MEMORIA DONDE SE GUARDA EL DATO
    RESULTADO EQU  0X21
         ORG    0X00               ;EL CODIGO SE ENSAMBLA EN LA DIRECCIÓN 0X00
         GOTO   CON_INICIALES	   ;IR A CON_INICIALES
CON_INICIALES:
         CLRF   DATO_1             ;SE COLOCA A CERO EL REGISTRO DATO_1
         CLRF   RESULTADO
         CLRW   
BUCLE:
         MOVLW  D'0'		;AQUI SE INTRODUCE UN DATO
							;EN ESTE CASO SE INTRODUCE UN CERO
							;PARA QUE EMPIECE A INCREMENTAR DESDE 0
         MOVWF  DATO_1		;MUEVE EL VALOR DEL REFISTRO 'W' AL REGISTRO DATO_1  
NUM_VECES:
         INCF   DATO_1,F    ;INCREMENTA EL REGISTRO 'DATO_1' Y SE GUARDA EN EL MISMO REGISTRO
;-----------LIMITE-----------------------------------------------------------------
         MOVLW  D'5'        ;ESTE ES EL LIMITE DONDE SE INCREMENTA SEGUN ESTE VALOR
         SUBWF  DATO_1,W    ;REALIZA UNA RESTA PARA CONTROLAR EL NUMERO DE VECES DE INCREMENTO
         BTFSS  STATUS,Z    ;ESTE ES UNA CONDICIONAL REALIZA UN SALTO SI EL BIT 'Z' ES 1
         GOTO   NUM_VECES   ;SI NO CUMPLE LA CONDICION NO SALTA Y EJECUTA 'GOTO NUM_VECES'
RESPUESTA:         
         MOVF   DATO_1,W	;MUEVE EL REGISTRO 'DATO_1' AL REGISTRO 'W'
         MOVWF  RESULTADO   ;MUEVE EL 'W' AL REGISTRO 'RESULTADO'
         GOTO   RESPUESTA   ;IR A ETIQUTA RESPUESTA
         END