Autor:Calle Condori Rodrigo
;DECREMENTA UNA UNIDAD Y SALTA CUANDO ES CERO
	LIST P=16F877A
	INCLUDE <P16F877A.INC>

	DATO_1	EQU  0X20      ;REGISTRO AUXILIAR DONDE SE GUARDA EL DATO

            ORG      0X00      ;DESDE ESTA DIRECCION SE ENSAMBLA EL CODIGO
            GOTO     INICIO    ;IR A LA ETUIQUETA INICIO
INICIO:
            MOVLW    D'10'     ;MOVER EL NUMERO 1O AL REGISTRO DE TRABAJO
            MOVWF    DATO_1    ;MOVER EL REGISTRO DE TRABAJO AL REGISTRO DATO_1
            DECFSZ   DATO_1,F  ;DECREMENTAR EL REGISTRO DATO_1 A UNA UNIDAD Y 
                               ;GUARDARLO EN EL MISMO REGISTRO DATO_1=DATO_1-1
                               ;SALTARA SI EL REGISTRO LLEAGA A VALER CERO
            GOTO     INICIO    ;
            GOTO     $        ;BUCLE INFINITO
            END